variables:
  image: archlinux:latest
  pacman_deps: cmake ninja gcc yaml-cpp
  pacman_deps_makepkg: rsync debugedit fakeroot git namcap
  pacman_deps_py: python python-pip

stages:
  - build
  - test

build_cpp:
  stage: build
  image: ${image}
  script:
    - pacman -Sy --noconfirm --needed ${pacman_deps}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/build.sh

build_makepkg:
  stage: build
  image: ${image}
  artifacts:
    paths:
      - structstore{,_py}-*.pkg.tar.zst
    expire_in: 1 hour
  script:
    - pacman -Sy --noconfirm --needed ${pacman_deps} ${pacman_deps_py} ${pacman_deps_makepkg}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/makepkg.sh
    - cp /tmp/structstore_build/structstore{,_py}-*.pkg.tar.zst ./

build_py:
  stage: build
  image: ${image}
  artifacts:
    paths:
      - dist/structstore-*.{tar.gz,whl}
    expire_in: 1 hour
  script:
    - pacman -Sy --noconfirm --needed ${pacman_deps} ${pacman_deps_py}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/build_py.sh
