variables:
  image: archlinux:latest
  pacman_deps: cmake ninja gcc yaml-cpp
  pacman_deps_makepkg: rsync fakeroot git namcap
  pacman_deps_py: python python-pip
  pacman_deps_test: gtest
  pacman_deps_pytest: python-pytest python-numpy

stages:
  - build
  - test

build_cpp:
  stage: build
  image: ${image}
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/build.sh

test_cpp:
  stage: test
  image: ${image}
  needs: [build_cpp]
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_test}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c "BUILD_WITH_TESTING=1 ./scripts/build.sh"

build_py:
  stage: build
  image: ${image}
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_py}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c "BUILD_WITH_PYTHON=1 ./scripts/build.sh"

test_py:
  stage: test
  image: ${image}
  needs: [build_py]
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_py} ${pacman_deps_test}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c "BUILD_WITH_PYTHON=1 BUILD_WITH_TESTING=1 ./scripts/build.sh"
    # todo: make package available and run python tests

build_archlinux:
  stage: build
  image: ${image}
  artifacts:
    paths:
      - structstore{,_py}-*.pkg.tar.zst
    expire_in: 1 hour
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_py} ${pacman_deps_makepkg}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/makepkg.sh
    - cp /tmp/structstore_build/structstore{,_py}-*.pkg.tar.zst ./

test_archlinux_cpp:
  stage: test
  image: ${image}
  needs: [build_archlinux]
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_test}
    - pacman -U --noconfirm ./structstore-*.pkg.tar.zst
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/test.sh

test_archlinux_py:
  stage: test
  image: ${image}
  needs: [build_archlinux]
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_py} ${pacman_deps_test} ${pacman_deps_pytest}
    - pacman -U --noconfirm ./structstore{,_py}-*.pkg.tar.zst
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c "BUILD_WITH_PYTHON=1 ./scripts/test.sh"

build_pywheel:
  stage: build
  image: ${image}
  artifacts:
    paths:
      - dist/structstore-*.{tar.gz,whl}
    expire_in: 1 hour
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_py}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c ./scripts/build_py.sh

test_pywheel:
  stage: test
  image: ${image}
  needs: [build_pywheel]
  script:
    - pacman -Syu --noconfirm --needed ${pacman_deps} ${pacman_deps_py} ${pacman_deps_test}
    - chmod a+rX -R .
    - su nobody -s /bin/bash -c "BUILD_WITH_PYTHON=1 BUILD_WITH_VENV=1 ./scripts/test.sh"
