variables:
  image: archlinux:latest
  pacman_deps_cpp: cmake ninja gcc yaml-cpp namcap
  pacman_deps_py: python-pip

stages:
  - build
  - test

build_cpp:
  stage: build
  image: ${image}
  artifacts:
    - build/structstore-*.pkg.tar
  script:
    - pacman -Sy --noconfirm --needed ${pacman_deps_cpp}
    - mkdir build && cd build && ln -s ../PKGBUILD ./
    - git clone .. src/structstore
    - makepkg --noextract --holdver
    - namcap structstore-*.pkg.tar

build_python:
  stage: build
  image: ${image}
  script:
    - pacman -Sy --noconfirm --needed ${pacman_deps}
    - venvdir="$PWD/venv"
    - python -m venv "${venvdir}"
    - source "${venvdir}/bin/activate"
    - pip install -r requirements.txt
    - mkdir build && cd build && cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release && cd ..
    - cmake --build build --target install
    - pip install .
    - mkdir build_test && cd build_test && cmake ../examples -GNinja -DCMAKE_BUILD_TYPE=Release && cd ..
    - cmake --build build
