enable_testing()
find_package(GTest REQUIRED)

set(TEST_TARGETS "")
list(APPEND TEST_TARGETS test_basic_0)
list(APPEND TEST_TARGETS test_basic_1)

foreach(TEST_TARGET ${TEST_TARGETS})
    add_executable(${TEST_TARGET} ${STRUCTSTORE_TESTS_DIR}/${TEST_TARGET}.cpp)
    add_test(NAME ${TEST_TARGET} COMMAND ${TEST_TARGET})
endforeach()

if(${BUILD_WITH_PYTHON})
    add_structstore_binding(mystruct0_py ${STRUCTSTORE_TESTS_DIR}/mystruct0_py.cpp)
    list(APPEND TEST_TARGETS mystruct0_py)
endif()

foreach(TEST_TARGET ${TEST_TARGETS})
    target_compile_features(${TEST_TARGET} PUBLIC cxx_std_17)
    target_compile_options(${TEST_TARGET} PUBLIC -Wall -Wextra -pedantic -Werror)
    target_include_directories(${TEST_TARGET} PRIVATE ${STRUCTSTORE_INCLUDE_DIR})
    target_link_libraries(${TEST_TARGET} PRIVATE structstore_lib ${GTEST_BOTH_LIBRARIES})
    if(${BUILD_WITH_SANITIZER})
        target_compile_options(${TEST_TARGET} PRIVATE -fsanitize=address)
        target_link_libraries(${TEST_TARGET} PRIVATE -fsanitize=address)
    endif()
endforeach()
